# Generated by Django 4.2.7 on 2024-12-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161231_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='open_locality',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
