# Generated by Django 4.2.16 on 2024-12-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('battles', '0003_alter_positionedfigher_fighter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='blue_placement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_blue', to='battles.placement'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='red_placement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='battles_as_red', to='battles.placement'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo'),
        ),
    ]
