# Generated by Django 4.2.16 on 2024-12-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0005_alter_battle_result_alter_fighter_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='kind',
            field=models.CharField(choices=[('archer', 'archer'), ('berserker', 'berserker'), ('cavalry', 'cavalry'), ('commander', 'commander'), ('knight', 'knight'), ('infantryman', 'infantryman')], max_length=16),
        ),
    ]
