# Generated by Django 4.2.16 on 2024-12-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_alter_battle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='kind',
            field=models.CharField(choices=[('archer', 'archer'), ('berserker', 'berserker'), ('cavalry', 'cavalry'), ('commander', 'commander'), ('knight', 'knight'), ('guardsman', 'guardsman'), ('infantryman', 'infantryman'), ("{('archer', 'archer'): 5, ('berserker', 'berserker'): 9, ('cavalry', 'cavalry'): 13, ('commander', 'commander'): 8, ('guardsman', 'guardsman'): 14, ('knight', 'knight'): 15, ('infantryman', 'infantryman'): 7}", 'Hp Choices')], max_length=256),
        ),
    ]
